import Foundation

// Temporary ViewModel structure matching the Rust ViewModel
// TODO: This should be generated by TypeGen once we solve the Uuid tracing issue
struct ViewModel: Codable {
    let count: String
}

@MainActor
class Core: ObservableObject {
    @Published var view: ViewModel
    
    init() {
        // Call the top-level view() function from the generated FFI
        let viewData = Thiccc.view()
        
        // Use JSON deserialization instead of bincode
        self.view = try! JSONDecoder().decode(ViewModel.self, from: Data(viewData))
    }
    
    func update() {
        // TODO: Implement event handling once we solve type generation
        // For now, just refresh the view
        let viewData = Thiccc.view()
        self.view = try! JSONDecoder().decode(ViewModel.self, from: Data(viewData))
    }
}
