/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct RustCore RustCore;

/**
 * Create a new Rust core instance
 * Returns a pointer to the core instance
 */
RustCore *rust_core_new(void);

/**
 * Free a Rust core instance
 */
void rust_core_free(RustCore *core);

/**
 * Dispatch an event to the core
 * event_json: JSON string of the event
 * Returns: JSON string of the view model, or NULL on error
 * Caller must free the returned string using rust_string_free()
 */
char *rust_core_dispatch(RustCore *core, const char *event_json);

/**
 * Get the current view model
 * Returns: JSON string of the view model, or NULL on error
 * Caller must free the returned string using rust_string_free()
 */
char *rust_core_view(const RustCore *core);

/**
 * Free a string returned from Rust
 */
void rust_string_free(char *s);

