name: Sharp9
options:
  bundleIdPrefix: com.cuzzos
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  Sharp9:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sharp9
        excludes:
          - Tests
    settings:
      base:
        DEVELOPMENT_TEAM: WGS9LUKK32
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: false
    info:
      path: Sharp9/Info.plist
      properties:
        CFBundleDisplayName: sharp9
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
