# XcodeGen Project Specification for thiccc
# This file can generate a proper Xcode project
# Install XcodeGen: brew install xcodegen
# Generate project: xcodegen generate

name: thiccc
options:
  bundleIdPrefix: com.thiccc
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en

settings:
  base:
    PRODUCT_NAME: thiccc
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_PREVIEWS: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  thiccc:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    
    sources:
      - path: thiccc
        excludes:
          - "*.md"
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.thiccc.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES

