name: Thiccc
projectReferences:
  Shared:
    path: ../shared/shared.xcodeproj
packages:
  SharedTypes:
    path: ../shared_types/generated/swift/SharedTypes
options:
  bundleIdPrefix: com.cuzzos.Thiccc
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  Thiccc:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Thiccc
      - path: ../shared/src/shared.udl
        buildPhase: sources
    dependencies:
      - target: Shared/shared-staticlib
      - package: SharedTypes
    info:
      path: Thiccc/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
    settings:
      OTHER_LDFLAGS: [-w]
      SWIFT_OBJC_BRIDGING_HEADER: generated/sharedFFI.h
      ENABLE_USER_SCRIPT_SANDBOXING: NO
    preBuildScripts:
      - name: Build uniffi-bindgen for macOS
        script: |
          #!/bin/bash
          set -e
          
          # Build uniffi-bindgen as a native macOS tool using cargo
          cd "${PROJECT_DIR}/.."
          
          # Ensure cargo is in PATH
          export PATH="$HOME/.cargo/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"
          
          # Create build output directory
          mkdir -p shared/build/Debug
          
          # Build uniffi-bindgen for the host (macOS) - always use debug for faster builds
          # (this is a build tool, not part of the shipped app)
          cargo build --bin uniffi-bindgen
          
          # Copy to a consistent location in shared/build
          cp target/debug/uniffi-bindgen shared/build/Debug/uniffi-bindgen
    buildRules:
      - name: Generate FFI
        filePattern: "*.udl"
        script: |
          #!/bin/bash
          set -e

          # Skip during indexing phase in XCode 13+
          if [ "$ACTION" == "indexbuild" ]; then
            echo "Not building *.udl files during indexing."
            exit 0
          fi

          # Skip for preview builds
          if [ "$ENABLE_PREVIEWS" = "YES" ]; then
            echo "Not building *.udl files during preview builds."
            exit 0
          fi

          cd "${INPUT_FILE_DIR}/.."
          # uniffi-bindgen is built for macOS in the shared project's build directory
          UNIFFI_BINDGEN="${PROJECT_DIR}/../shared/build/Debug/uniffi-bindgen"
          if [ ! -f "$UNIFFI_BINDGEN" ]; then
            echo "Error: uniffi-bindgen not found at $UNIFFI_BINDGEN"
            echo "Expected location: ${PROJECT_DIR}/../shared/build/Debug/uniffi-bindgen"
            echo "The prebuild script should have built it."
            exit 1
          fi
          "$UNIFFI_BINDGEN" generate "src/${INPUT_FILE_NAME}" --language swift --out-dir "${PROJECT_DIR}/generated"
        outputFiles:
          - $(PROJECT_DIR)/generated/$(INPUT_FILE_BASE).swift
          - $(PROJECT_DIR)/generated/$(INPUT_FILE_BASE)FFI.h
        runOncePerArchitecture: false
